### ISSUE TITLE
What's wrong with the website?

### ISSUE THREAD

**Issue by shivamdixit** [LNMIIT-FOSS/lnmiit-foss.github.io#20]
All the sections are messed up. For example, FAQ:

<img width="848" alt="screen shot 2016-01-02 at 8 21 19 am" src="https://cloud.githubusercontent.com/assets/3061095/12072993/eb898ab6-b129-11e5-8ece-4e7ec663fe2c.png">

Here is another section:
<img width="511" alt="screen shot 2016-01-02 at 8 22 32 am" src="https://cloud.githubusercontent.com/assets/3061095/12073000/30823942-b12a-11e5-9810-8eebd0002303.png">

Is the website complete or still WIP? If it's not complete I think it would be better to mention somewhere on the top that website is under construction.

**Comment by bhush9** [comment]
There is one issue that it tries to load one CSS from http while conf.kde.in being HTTPS.. I will correct it in production

**Comment by shivamdixit** [comment]
@bhush9 Yeah I just saw that, thanks.

**Comment by shivamdixit** [comment]
@bhush9 I've fixed the issue in the code, how is the deployment process happening? Is it manually deployed through FTP?

**Comment by sagaragarwal94** [comment]
I have fixed all the major ones and only student registration is pending. We need a account for it. It will be done today.
