### ISSUE TITLE
Responsive Check for the website

### ISSUE THREAD

**Issue by sagaragarwal94** [LNMIIT-FOSS/lnmiit-foss.github.io#21]
There are minor responsive fall through failures. 

The image is http://i.imgur.com/8iQW3jE.png.

@jamesthechamp do the corrections and @mudithkr look into it.

**Comment by mudithkr** [comment]
One more is there having responsiveness issues. ![znc1](https://cloud.githubusercontent.com/assets/9371152/12073961/79060a3c-b160-11e5-9481-7f06e43b12bf.png)

**Comment by sagaragarwal94** [comment]
@jainmukul Please have a look.

**Comment by sagaragarwal94** [comment]
Closed.
