### ISSUE TITLE
"Participate" link is broken

### ISSUE THREAD

**Issue by shivamdixit** [LNMIIT-FOSS/lnmiit-foss.github.io#22]
<img width="1170" alt="screen shot 2016-01-05 at 10 20 19 am" src="https://cloud.githubusercontent.com/assets/3061095/12107823/33f01374-b396-11e5-95b8-a5cc03f36df7.png">

**Comment by bhush9** [comment]
aye, it will take max 1 or 2 days for doattend to publish page.

**Comment by sagaragarwal94** [comment]
It is not broken. We have to add current account to accept student registrations. This will start on 11 January. I am talking to college authoritiy to provide us the account hence to avoid income tax issues.

**Comment by shivamdixit** [comment]
@sagaragarwal94 
> It is not broken.
The link which is not working as *intended* is indeed a *BROKEN* link ;-)

The website is already being published on social media, the first thing people do is to click on participate. Showing them a `404` page is not really a bright idea. IMO it will be better to show them an alert/popul saying "Coming Soon" / "Check Back Soon", or something like that. We don't want to loose any single  interested student, right?

@bhush9 Thanks for the info :)

**Comment by sagaragarwal94** [comment]
I am on it.

**Comment by shivamdixit** [comment]
@sagaragarwal94 Thanks for the heads up

**Comment by sagaragarwal94** [comment]
Done

**Comment by sagaragarwal94** [comment]
@shivamdixit if it is ok then @bhush9, please push the code to conf.kde.in repo.

**Comment by shivamdixit** [comment]
@sagaragarwal94 Go ahead

**Comment by sagaragarwal94** [comment]
@bhush9 please merge the changes to conf.kde.in

**Comment by bhush9** [comment]
synced.
