### ISSUE TITLE
Description missing from speaker's profile

### ISSUE THREAD

**Issue by vjs3** [LNMIIT-FOSS/lnmiit-foss.github.io#23]
On clicking on the speaker's profile there is no description has been provided.We can also add their github and linkedin profile so that people can know who they actually are.

**Comment by sagaragarwal94** [comment]
Working on it. Thanks. assigned to @jainmukul .

**Comment by sagaragarwal94** [comment]
Closed with https://github.com/LNMIIT-FOSS/lnmiit-foss.github.io/pull/25.

**Comment by vjs3** [comment]
@sagaragarwal94 Still no details has been added to the speakers.

**Comment by sagaragarwal94** [comment]
@vjs3 Sure I will update that.

**Comment by sagaragarwal94** [comment]
@jainmukul, this is still remaining.

**Comment by sagaragarwal94** [comment]
No need on that.
