### ISSUE TITLE
Hyperlinks has been directly used everywhere

### ISSUE THREAD

**Issue by vjs3** [LNMIIT-FOSS/lnmiit-foss.github.io#27]
Hyperlinks are directly used in the entire website specially in the Frequently asked questions section.Images are attached below.I have fixed this, please reiew my PR.
![screenshot 161 1](https://cloud.githubusercontent.com/assets/11405622/12430717/1b8563b6-bf17-11e5-9899-3e962017feb9.png)
![screenshot 162 1](https://cloud.githubusercontent.com/assets/11405622/12430718/1b9980f8-bf17-11e5-8201-21d228d899b6.png)

**Comment by sagaragarwal94** [comment]
@vjs3 Thanks for the update. Merged :)
