### ISSUE TITLE
Website become responsive but not the clock portion and maps

### ISSUE THREAD

**Issue by vjs3** [LNMIIT-FOSS/lnmiit-foss.github.io#31]
There is still issues with responsiveness in the the clock portion as far as I know this is because of some jquery issue, please check it out guys.I would suggest if that is not becoming responsive then use some other time.There is also issues with maps as it is not centered in the mobile phone else everything is fine.

**Comment by sagaragarwal94** [comment]
@vjs3 That is a fixed part and if you can resolve it. it is cool. Looking forward for the pull request :)

**Comment by sagaragarwal94** [comment]
Do you want it to get it assigned?

**Comment by vjs3** [comment]
I am going home tomorrow so would not be able to do it, it would be better
if you assign it to someone can do it.



Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=vishwajeets912@gmail.com&idSignature=22>

*Vishwajeet Srivastava*
B.Tech, Pre-Final (Computer Science and Engineering)
The LNM Institute of Information Technology
Mob:+91-9461787316

**Comment by sagaragarwal94** [comment]
done.
