### ISSUE TITLE
Contact Us button is out of top bar

### ISSUE THREAD

**Issue by ayushagrawal288** [LNMIIT-FOSS/lnmiit-foss.github.io#33]
contact us button is outside the top bar and appearing below the top bar

**Comment by sagaragarwal94** [comment]
Assigning it to @jainmukul

**Comment by jainmukul** [comment]
I cant see any problem... screen shots plz.

**Comment by mudithkr** [comment]
![znc7](https://cloud.githubusercontent.com/assets/9371152/12813429/eee20870-cb5d-11e5-94f4-012b61dd7db6.png)

**Comment by bhush9** [comment]
I guess I mentioned that long ago.. :stuck_out_tongue_winking_eye:

**Comment by jainmukul** [comment]
There is no logo i guess

**Comment by mudithkr** [comment]
@jainmukul  the contact button also slide down home button if u can see it.

**Comment by jainmukul** [comment]
@mudithkr screenshots -_-

**Comment by mudithkr** [comment]
@jainmukul 4th comment is screenshot

**Comment by ayushagrawal288** [comment]
@jainmukul  Have you got a chance to look at it??

**Comment by jainmukul** [comment]
Thanks to Mudit, @mudithkr

**Comment by mudithkr** [comment]
welcome @jainmukul :)
